language: ruby
before_install: gem install bundler -v 1.10.2
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - rbx-2
  - ruby-head
notifications:
  email:
    recipients:
      - shane@teamsnap.com
      - kyle.ries@teamsnap.com
