language: ruby
before_install:
  - "find /home/travis/.rvm/rubies -wholename '*default/bundler-*.gemspec' -delete"
  - gem install bundler -v 1.15.2
rvm:
  - 2.3.1
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
